### ISSUE TITLE
Unexpected Error on Run

### ISSUE THREAD

**Issue by drobins7MAC** [Nuix/Export-Profile-Plus#8]
Unexpected Error
 
Message:
(LoadError) no such file to load -- C:/ProgramData/Nuix/Scripts/Export-Profile-Plus-master/Ruby/ExportProfilePlus.nuixscript/Nx
Stack Trace:
org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- C:/ProgramData/Nuix/Scripts/Export-Profile-Plus-master/Ruby/ExportProfilePlus.nuixscript/Nx
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:131)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.nuix.script.e.a(SourceFile:62)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.nuix.script.e.a(SourceFile:59)
	at com.sun.proxy.$Proxy56.eval(Unknown Source)
	at com.nuix.script.a.a(SourceFile:289)
	at com.nuix.investigator.script.m.e(SourceFile:326)
	at com.nuix.investigator.script.m.c(SourceFile:277)
	at com.nuix.investigator.script.m.doInBackground(SourceFile:180)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- C:/ProgramData/Nuix/Scripts/Export-Profile-Plus-master/Ruby/ExportProfilePlus.nuixscript/Nx	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
	at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:59)
	at RUBY.<main>(C:\ProgramData\Nuix\Scripts\Export-Profile-Plus-master\Ruby\ExportProfilePlus.nuixscript\ExportProfilePlus.rb:11)

**Comment by JuicyDragon** [comment]
Worked out elsewhere:
Downloading a clone of the source code using the big green "Clone or Download" button lacks the compiled Nx.jar.  Instead downloading a [release](https://github.com/Nuix/Export-Profile-Plus/releases) will provide you with what you need to run the script including compiled dependencies.
